name: flutter1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7    # Tambahkan baris ini untuk package flutter_svg
  connectivity_plus: ^6.0.5
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  http: ^1.2.2
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/speedtest.svg
    - assets/icons/sniffing.svg
    - assets/icons/terminal.svg
    - assets/icons/vpn.svg
    - assets/icons/files.svg
    - assets/icons/save.svg
    - assets/icons/start.svg
    - assets/icons/stop.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
    - family: CONSOLA
      fonts:
        - asset: assets/fonts/CONSOLA.TTF
          weight: 400
        - asset: assets/fonts/CONSOLAI.TTF
          style: italic
        - asset: assets/fonts/CONSOLAB.TTF
          weight: 700
        - asset: assets/fonts/CONSOLAZ.TTF
          weight: 700
          style: italic