name: flutter1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7    # Tambahkan baris ini untuk package flutter_svg
  connectivity_plus: ^6.0.5
  flutter_network_inspector: ^0.1.8
  http: ^1.2.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  share_plus: ^10.1.1
  open_file: ^3.5.9
  speed_test_dart: ^1.0.5+0
  shared_preferences: ^2.3.2
  dartssh2: ^2.10.0
  file_picker: ^8.1.3
  dart_ping: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/speedtest.svg
    - assets/icons/sniffing.svg
    - assets/icons/terminal.svg
    - assets/icons/vpn.svg
    - assets/icons/files.svg
    - assets/icons/save.svg
    - assets/icons/start.svg
    - assets/icons/stop.svg
    - assets/icons/share.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.TTF
          weight: 400
        - asset: assets/fonts/ProductSans-Bold.TTF
          weight: 700
        - asset: assets/fonts/ProductSans-Italic.TTF
          weight: 400
          style: italic
        - asset: assets/fonts/ProductSans-BoldItalic.TTF
          weight: 700
          style: italic
    - family: Consolas
      fonts:
        - asset: assets/fonts/CONSOLA.TTF
          weight: 400
        - asset: assets/fonts/CONSOLAB.TTF
          weight: 700
        - asset: assets/fonts/consolai.TTF
          weight: 400
          style: italic
        - asset: assets/fonts/consolaz.TTF
          weight: 700
          style: italic