// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtYGLnzR49n1YYZtPlerfeTqwTIeYFF3A',
    appId: '1:875567832331:web:ffa40db4c2d90384d8d60e',
    messagingSenderId: '875567832331',
    projectId: 'flutter1-4ea3b',
    authDomain: 'flutter1-4ea3b.firebaseapp.com',
    storageBucket: 'flutter1-4ea3b.appspot.com',
    measurementId: 'G-5VVJYRR5PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVzGFJ6k1hnhNjeM0GAJ6w1ibrkgxPo6s',
    appId: '1:875567832331:android:60f29e7c4a84334ed8d60e',
    messagingSenderId: '875567832331',
    projectId: 'flutter1-4ea3b',
    storageBucket: 'flutter1-4ea3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_NhpUbepq3_wKBMfLi06C-6fJYc2zp0k',
    appId: '1:875567832331:ios:45fb7d0a924fc2ffd8d60e',
    messagingSenderId: '875567832331',
    projectId: 'flutter1-4ea3b',
    storageBucket: 'flutter1-4ea3b.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_NhpUbepq3_wKBMfLi06C-6fJYc2zp0k',
    appId: '1:875567832331:ios:45fb7d0a924fc2ffd8d60e',
    messagingSenderId: '875567832331',
    projectId: 'flutter1-4ea3b',
    storageBucket: 'flutter1-4ea3b.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtYGLnzR49n1YYZtPlerfeTqwTIeYFF3A',
    appId: '1:875567832331:web:438df40f0387c480d8d60e',
    messagingSenderId: '875567832331',
    projectId: 'flutter1-4ea3b',
    authDomain: 'flutter1-4ea3b.firebaseapp.com',
    storageBucket: 'flutter1-4ea3b.appspot.com',
    measurementId: 'G-JBY0WQR5C1',
  );
}
